### ISSUE TITLE
Upstream things

### ISSUE THREAD

**Issue by lazka** [centricular/pixman#2]
Just a note, in case anyone finds this repo:

https://gitlab.freedesktop.org/pixman/pixman contains its own meson build defs for some months now, but doesn't build with MSVC and there might be more differences, things missing.

Someone should try to push the remaining things contained here upstream.

**Comment by MathieuDuponchelle** [comment]
Done @ https://gitlab.freedesktop.org/pixman/pixman/merge_requests/25, not much was missing afaict :)

**Comment by lazka** [comment]
Awesome, thanks @MathieuDuponchelle !

**Comment by MathieuDuponchelle** [comment]
No problem, I should have upstreamed that ages ago, that would have spared duplicate work, but that's how it is :) I'll check on my other ports soon hopefully.
